CREATE DATABASE CALCDB;
USE CALCDB;

-- DATOS DE LOS USUARIOS.
CREATE TABLE datos(
    id INT(30) NOT NULL AUTO_INCREMENT,
    mail VARCHAR(30) NOT NULL,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(150) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (mail)
);